/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Control.clsHorarioDAO;
import Control.clsHorarioMedico;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class viewAsignarHorario extends javax.swing.JFrame {
     private clsHorarioDAO daoHorario = new clsHorarioDAO();
    /**
     * Creates new form viewAsignarHorario
     */
    public viewAsignarHorario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        lblHoraSalida = new javax.swing.JLabel();
        lblHoraInicio = new javax.swing.JLabel();
        lblIdMedico = new javax.swing.JLabel();
        BtnAsignarHorario = new javax.swing.JButton();
        txtHoraSalida = new javax.swing.JTextField();
        txtHoraInicio = new javax.swing.JTextField();
        txtIdMedico = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAnio = new javax.swing.JComboBox<>();
        lblIdPersona = new javax.swing.JLabel();
        txtIdPersona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(390, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("       ASIGNAR HORARIO MEDICO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        lblHoraSalida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHoraSalida.setText("Hora Salida:");
        getContentPane().add(lblHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        lblHoraInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHoraInicio.setText("Hora Inicio:");
        getContentPane().add(lblHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        lblIdMedico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdMedico.setText("ID Medico:");
        getContentPane().add(lblIdMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        BtnAsignarHorario.setText("Asignar Horario");
        BtnAsignarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAsignarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));
        getContentPane().add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 151, -1));
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 151, -1));
        getContentPane().add(txtIdMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 151, -1));

        lblFecha.setText("Fecha:");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.setToolTipText("");
        getContentPane().add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        cbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        getContentPane().add(cbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        lblIdPersona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdPersona.setText("Id Persona");
        getContentPane().add(lblIdPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        getContentPane().add(txtIdPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 151, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/AsignarHorarioMedico.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.setVisible(false);
        viewAdministrador jAdministrador = new viewAdministrador();
        jAdministrador.setVisible(true);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnAsignarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarHorarioActionPerformed
        //<editor-fold defaultstate="collapsed" desc="Asignación de variables">
        int varIdHorario = 1;
         try {
             varIdHorario = daoHorario.contarFilas();
         } catch (SQLException ex) {
             Logger.getLogger(viewAsignarHorario.class.getName()).log(Level.SEVERE, null, ex);
         }
        int varIdPersona = Integer.parseInt(txtIdPersona.getText());
        int varIdMedico = Integer.parseInt(txtIdMedico.getText());
        String varDia = cbDia.getSelectedItem().toString();
        String varMes = cbMes.getSelectedItem().toString();
        String varAnio = cbAnio.getSelectedItem().toString();
        String varFecha = varDia + "/" + varMes + "/" + varAnio;
        String varHoraEntrada = txtHoraInicio.getText();
        String varHoraSalida = txtHoraSalida.getText();
        String varEstado = "Libre"; 
        //</editor-fold>
        System.out.println("" + varIdHorario);
        clsHorarioMedico miHorario = new clsHorarioMedico(varIdHorario, varIdPersona, varIdMedico, varEstado, varFecha, varHoraEntrada, varHoraSalida);
        
        
        boolean varSeAsigno = false;
         try {
             varSeAsigno = daoHorario.asignarHorarioAtencion(miHorario);
         } catch (SQLException ex) {
             Logger.getLogger(viewAsignarHorario.class.getName()).log(Level.SEVERE, null, ex);
         }
        if(varSeAsigno == true)
        {
            JOptionPane.showMessageDialog(null, "Se asigno el horario al medico correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No se pudo asignar el horario al medico, por favor verifique los datos.");
        }
        
        
    }//GEN-LAST:event_BtnAsignarHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAsignarHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAsignarHorario;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> cbAnio;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblIdMedico;
    private javax.swing.JLabel lblIdPersona;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtIdMedico;
    private javax.swing.JTextField txtIdPersona;
    // End of variables declaration//GEN-END:variables
}
